## what is FROM used for ? what all things it can have ?

FROM adoptopenjdk/openjdk12

# what is EXPOSE used for ? is there other way u can have ?
EXPOSE 8080

# ADD ? what does it do ? what is difference with COPY ?
ADD ./target/gateway-0.0.1-SNAPSHOT.jar app.jar

# what is ENTRYPOINT ?
ENTRYPOINT ["java","-jar","/app.jar"]

# what are Best practices to use a Dockerfile with ? hint: start.sh

